
name: Basic Workflow Dispatch

on:
  workflow_dispatch:
    inputs: 
      base-directory:
        description: 'relative path in the repository of the root folder, in which to search for to search for protocols'
        required: false
        default: 'protocols'
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Analyze
        env:
          BASE_DIRECTORY: ${{ github.event.inputs.base-directory }}
        uses: DerekMaggio/ot-analyze@add-different-output-options


      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: analysis-results
          path: |
            ${{ github.workspace }}/protocols_and_analyses.zip
            ${{ github.workspace }}/summary.md
