
name: Basic Workflow Dispatch

on:
  workflow_dispatch:
    inputs: 
      base-directory:
        description: 'relative path in the repository of the root folder in which to search for to search for protocols'
        required: false
        default: 'protocols'
        type: string
      output-type:
        description: 'type of output the action generates'
        required: false
        default: 'none'
        type: choice
        options:
          - 'none'
          - 'zip'
          - 'markdown'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Analyze
        env:
          BASE_DIRECTORY: ${{ github.event.inputs.base-directory }}
          OUTPUT_TYPE: ${{ github.event.inputs.output-type }}
        uses: DerekMaggio/ot-analyze@add-different-output-options
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          base: ${{ github.head_ref }}
